version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - db-store13:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_app_dev
    ports:
      - 5432:5432
volumes:
  db-store13:
